-- H2 migration for the Fiche de renseignements Deces.
ALTER TABLE ayant_droit ADD COLUMN IF NOT EXISTS lieu_naissance VARCHAR(100);
ALTER TABLE ayant_droit ADD COLUMN IF NOT EXISTS situation_familiale VARCHAR(100);
ALTER TABLE ayant_droit ADD COLUMN IF NOT EXISTS niveau_instruction VARCHAR(120);
ALTER TABLE ayant_droit ADD COLUMN IF NOT EXISTS activite_emploi VARCHAR(160);

CREATE TABLE IF NOT EXISTS liquidations_droits_deces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dossier_id BIGINT NOT NULL,
  designation VARCHAR(60) NOT NULL, montant DECIMAL(19,2) NOT NULL, beneficiaire VARCHAR(160), reference VARCHAR(120),
  CONSTRAINT fk_liquidation_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers_deces(id)
);
CREATE TABLE IF NOT EXISTS pensions_deces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dossier_id BIGINT NOT NULL, ayant_droit_id BIGINT,
  type_beneficiaire VARCHAR(30) NOT NULL, numero VARCHAR(100), montant DECIMAL(19,2) NOT NULL,
  CONSTRAINT fk_pension_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers_deces(id),
  CONSTRAINT fk_pension_ayant FOREIGN KEY (ayant_droit_id) REFERENCES ayant_droit(id)
);
CREATE TABLE IF NOT EXISTS assurances_deces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dossier_id BIGINT NOT NULL, ayant_droit_id BIGINT,
  type_beneficiaire VARCHAR(30) NOT NULL, numero_cheque VARCHAR(100), montant DECIMAL(19,2) NOT NULL,
  CONSTRAINT fk_assurance_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers_deces(id),
  CONSTRAINT fk_assurance_ayant FOREIGN KEY (ayant_droit_id) REFERENCES ayant_droit(id)
);
CREATE TABLE IF NOT EXISTS situations_financieres_deces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dossier_id BIGINT NOT NULL UNIQUE,
  pmr DECIMAL(19,2), pmi DECIMAL(19,2), salaire DECIMAL(19,2), autres_ressources DECIMAL(19,2),
  eau_electricite DECIMAL(19,2), frais_medicaux DECIMAL(19,2), frais_scolarite DECIMAL(19,2), loyer DECIMAL(19,2), autres_charges DECIMAL(19,2),
  CONSTRAINT fk_situation_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers_deces(id)
);
CREATE TABLE IF NOT EXISTS assistances_octroyees_deces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dossier_id BIGINT NOT NULL,
  designation VARCHAR(40) NOT NULL, montant DECIMAL(19,2) NOT NULL, date DATE, cheque_reference VARCHAR(120),
  CONSTRAINT fk_assistance_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers_deces(id)
);