package com.social.servicesocial.dto;

import java.time.LocalDate;
import java.util.List;

import com.social.servicesocial.model.DossierStatut;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

public record RetraiteDossierRequest(
        @Size(max=255) String nomAr,
        @Size(max=255) String prenomAr,
        @Size(max=255) String lieuNaissance,
        @Size(max=255) String matriculeCorps,
        @Size(max=255) String categorie,
        @Size(max=255) String situationCategorie,
        Boolean pension,
        LocalDate dateEntreeService,
        @Size(max=255) String motifRadiationSanction,
        LocalDate dateDeces,
        @Size(max=255) String causeDeces,
        @Size(max=255) String natureDeces,
        @Size(max=255) String formationUnite,
        @Size(max=255) String derniereRegion,
        @Size(max=255) String telephoneGsm2,
        @Size(max=255) String email,
        @Size(max=255) String observation,
        @Size(max=255) String adresseEM,
        @Size(max=255) String code,
        @Size(max=255) String carteFondation,
        @Size(max=255) String numeroPmr,
        @Size(max=255) String montantPmr,
        @Size(max=255) String numeroPmi,
        @Size(max=255) String montantPmi,
        @Size(max=255) String professionActuelle,
        @Size(max=255) String colisRamadan,
        @Size(max=255) String regionResidence,
        @Size(max=255) String hayRabat,
        @Size(max=255) String observationSociale,
        @Size(max=255) String motifEnquete,
        @Size(max=255) String numeroDossier,
        @Size(max=255) String cartePrelevementCmr,
        @Size(max=255) String situationFraternelle,
        @Size(max=255) String anneeAdhesion,
        @Size(max=255) String modeReglement,
        @Size(max=255) String numeroRecu,
        @Size(max=255) String datePaiement,
        @Size(max=255) String observationAdhesion,
        Boolean avecPhoto,
        @jakarta.validation.Valid @jakarta.validation.constraints.Size(max=8) List<@NotNull RetraitePieceDto> pieces,
        @Size(max=2796250) @Pattern(regexp="^$|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}") String photo,
        @Positive Long adherentId,
        @NotBlank @Size(max=100) String nom,
        @NotBlank @Size(max=100) String prenom,
        @NotBlank @Size(max=50) String matricule,
        @NotBlank @Size(max=50) String cin,
        @Size(max=50) String matriculeBr,
        @Size(max=80) String grade,
        LocalDate dateNaissance,
        LocalDate dateRadiation,
        @Size(max=255) String motif,
        @NotBlank @Size(max=50) String telephoneGsm,
        @Size(max=50) String telephoneFixe,
        @Size(max=150) String affectation,
        @Size(max=500) String adresse,
        @Size(max=80) String situationFamiliale,
        @Size(max=120) String habitation,
        boolean proprietaire,
        boolean locataire,
        @Size(max=500) String habitationPrecision,
        LocalDate dateEnquete,
        DossierStatut statut, @Valid List<@NotNull RetraiteAffiliationDto> affiliations,
        @Valid List<@NotNull RetraiteMembreFamilleDto> famille, @Valid List<@NotNull RetraiteMedicalDto> donneesMedicoSociales,
        @Valid List<@NotNull RetraiteAssistanceDto> assistances, @Valid List<@NotNull RetraiteBudgetDto> ressources,
        @Valid List<@NotNull RetraiteBudgetDto> charges
) {}
