spring.application.name=service-social-backend

spring.datasource.url=jdbc:oracle:thin:@//192.168.110.11:1521/carb
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${DB_USERNAME:SRV_SOC}
spring.datasource.password=${DB_PASSWORD:SRV_SOC}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=SRV_SOC

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.h2.console.enabled=false

app.cors.allowed-origins=http://localhost:4200

app.jwt.secret=4f6af64a4fb84779bb2e45f608e816f34f3b87776f4a45d087efecf5674e4dd9
app.jwt.expiration-ms=86400000
