spring.application.name=service-social-backend

spring.datasource.url=jdbc:h2:file:./data/service_social;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.cors.allowed-origins=http://localhost:4200

app.jwt.secret=4f6af64a4fb84779bb2e45f608e816f34f3b87776f4a45d087efecf5674e4dd9
app.jwt.expiration-ms=86400000
